// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// random_unif_interval
NumericVector random_unif_interval(int size, int max_val);
RcppExport SEXP _MOSim_random_unif_interval(SEXP sizeSEXP, SEXP max_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_val(max_valSEXP);
    rcpp_result_gen = Rcpp::wrap(random_unif_interval(size, max_val));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _sparsim_random_unif_interval(void *, void *);

static const R_CallMethodDef CallEntries[] = {
    {"_MOSim_random_unif_interval", (DL_FUNC) &_MOSim_random_unif_interval, 2},
    {"_sparsim_random_unif_interval", (DL_FUNC) &_sparsim_random_unif_interval, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_MOSim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
