# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

random_unif_interval <- function(size, max_val) {
    .Call(`_MOSim_random_unif_interval`, size, max_val)
}

